# buildspec.yml - CodeBuild Configuration
version: 0.2

phases:
  pre_build:
    commands:
      - echo "Starting PortTrack build..."
      - aws --version
      
  build:
    commands:
      - echo "Build started on `date`"
      # Simple validation for static files
      - |
        if [ ! -f "index.html" ]; then
          echo "ERROR: index.html not found"
          exit 1
        fi
      - echo "Basic security scan"
      - grep -r "javascript:" . && exit 1 || echo "No XSS found"
      
  post_build:
    commands:
      - echo "Build completed on `date`"
      - echo "Creating deployment package..."

artifacts:
  files:
    - '**/*'
  base-directory: '.'
  
cache:
  paths:
    - '/root/.cache/**/*'